# Generated by Django 4.0.3 on 2022-04-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_travelform_delete_formcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelform',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
